// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-C2Bb8Ogu1ejECSupcEcnbkaIeavJwKY',
    appId: '1:845168107634:android:ca23bc3c399233370862eb',
    messagingSenderId: '845168107634',
    projectId: 'practo-9b6f5',
    storageBucket: 'practo-9b6f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmviw6rowFmDoVXLv5Vs3Ri2GmcIu7a4I',
    appId: '1:845168107634:ios:9c7d856f94302c080862eb',
    messagingSenderId: '845168107634',
    projectId: 'practo-9b6f5',
    storageBucket: 'practo-9b6f5.appspot.com',
    androidClientId: '845168107634-95hnjba0vrc6pntlis4vh696o7468ig4.apps.googleusercontent.com',
    iosClientId: '845168107634-afdotmdshhdt6a0j1abnqmi7lrduje78.apps.googleusercontent.com',
    iosBundleId: 'com.zyron.app',
  );

}